# Generated by Django 4.0.2 on 2022-02-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_cart_price_cart_product_cart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.CharField(max_length=150),
        ),
    ]
